[blue1_server]
blue1-snapshot ansible_host=10.100.2.10     

[blue2_server]
blue2-snapshot ansible_host=10.100.3.10   

[iis_server:children]
blue1_server
blue2_server

[all:vars]
ansible_user=greyteam
ansible_password='Hockey123!'
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

