[blue1_server]
blue1-snapshot ansible_host=10.100.2.10

[blue2_server]
blue2-snapshot ansible_host=10.100.3.10

[iis_server:children]
blue1_server
blue2_server

[all:vars]
ansible_connection=winrm
ansible_user=ansible
ansible_password='DeployWindows123!'
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_scheme=https
ansible_port=5986
