---
- name: Deploy Monitoring Grafana Agents
  hosts: agents
  become: true

  vars:
    loki_server_ip: "{{ '10.100.2.7' if inventory_hostname in groups['blue1_agents'] else '10.100.3.7' }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Grafana GPG and Repo (Manual Shell)
      shell: |
        curl -fsSL https://apt.grafana.com/gpg.key | gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg
        echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" > /etc/apt/sources.list.d/grafana.list
      args:
        creates: /etc/apt/sources.list.d/grafana.list

    - name: Force apt update and install Alloy
      shell: |
        apt-get update
        apt-get install -y alloy prometheus-node-exporter- name: Download Grafana GPG key
      shell: |
        curl -fsSL https://apt.grafana.com/gpg.key | gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg
      args:
        creates: /etc/apt/keyrings/grafana.gpg

    - name: Install Node Exporter and Alloy
      apt:
        name: [prometheus-node-exporter, alloy]
        state: present
        update_cache: yes

    - name: Ensure Node Exporter is started and enable
      systemd:
        name: prometheus-node-exporter
        state: started
        enabled: true

    - name: Open Firewall fro Metrics ( Port 9100)
      ufw:
        rule: allow
        port: '9100'
        proto: tcp

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
        state: present
        filename: grafana
        update_cache: yes

    - name: ADD Alloy user to necessary groups
      user:
        name: alloy
        groups: adm,systemd-journal
        append: yes
      notify: Restart Alloy

    - name: Configure Alloy
      copy:
        dest: /etc/alloy/config.alloy
        content: |
          logging { level = "info" }

          loki.relabel "journal" {
            forward_to = [loki.write.local.receiver]
            rule { source_labels = ["__journal__systemd_unit"], target_label = "unit" }
          }

          loki.source.journal "read" {
            forward_to = [loki.relabel.journal.receiver]
          }

          local.file_match "mysql" {
            path_targets = [
              { "__address__" = "localhost", "filename" = "/var/log/mysql/*.log", "job" = "mysql_files" },
            ]
          }

          loki.source.file "mysql" {
            targets    = local.file_match.mysql.targets
            forward_to = [loki.write.local.receiver]
          }

          local.file_match "nginx" {
            path_targets = [
              { "__address__" = "localhost", "filename" = "/var/log/nginx/*.log", "job" = "nginx_files" },
            ]
          }

          loki.source.file "nginx" {
            targets    = local.file_match.nginx.targets
            forward_to = [loki.write.local.receiver]
          }

          loki.write "local" {
            endpoint {
              url = "http://10.100.3.7:3100/loki/api/v1/push"
            }
          }      
      notify: Restart Alloy

    - name: Enable MySQL General and Error Logging
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^#?general_log_file", line: "general_log_file = /var/log/mysql/query.log" }
        - { regexp: "^#?general_log\\s*=", line: "general_log = 1" }
        - { regexp: "^#?log_error", line: "log_error = /var/log/mysql/error.log" }
      when: (inventory_hostname == "10.100.2.5") or (inventory_hostname =="10.100.3.5")
      notify: Restart MySQL

    - name: Ensure MySQL log directory permissions
      file:
        path: /var/log/mysql
        state: directory
        owner: mysql
        group: adm
        mode: '0750'
      when: (inventory_hostname == "10.100.2.5") or (inventory_hostname =="10.100.3.5")

  handlers:
    - name: Restart Alloy
      systemd:
        name: alloy
        state: restarted

    - name: Restart MySQL
      systemd:
        name: mysql
        state: restarted
