---
-  name: Install and configure granfana
   hosts: [server]
   become: true

#variables used to conifgure Grafana settings 
   vars:
     grafana_http_port: 3000
     grafana_root_url: "http://{{ inventory_hostname }}:{{grafana_http_port}}/"
     grafana_admin_user: admin
     grafana_admin_password: "Password123!" # change this!!

#Mains task to install and configure grafana
   tasks:
    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
          - gnupg
          - ufw
        state: present
        update_cache: true

    - name: Add Grafana GPG key (Shell version)
      shell: |
        curl -fsSL https://apt.grafana.com/gpg.key | gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg
      args:
        creates: /etc/apt/keyrings/grafana.gpg

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
        state: present
        filename: grafana
#Install grafana Repository
    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: true

#configure basic Grafana setting suck as port and domain
    - name: Configure grafana.ini (minimal settings)
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: "^#?{{ item.key }}\\s*="
        line: "{{ item.key }} = {{ item.value }}"
        state: present
      loop:
        - { key: "http_port", value: "{{ grafana_http_port }}" }
        - { key: "domain", value: "{{ inventory_hostname}}" }
        - { key: "root_url", value: "{{ grafana_root_url }}" }
      notify: Restart grafana

    - name: Open ports
      ufw:
        rule: allow
        port: "{{item}}"
        proto: tcp
      loop: ['3000', '3100']
#ensure Grafana service is enabled and running 
    - name: Ensure Grafana is enabled and running
      systemd:
        name: grafana-server
        enabled: true
        state: started
    - name: Creake Loki group
      group:
        name: loki
        state: present
    - name: Create Loki user
      user:
        name: loki
        group: loki
        shell: /sbin/nologin
        system: yes

    - name: Download Loki binary (Shell version)
      shell: |
        curl -L "https://github.com/grafana/loki/releases/download/v2.9.4/loki-linux-amd64.zip" -o /tmp/loki.zip
      args:
        creates: /tmp/loki.zip

    - name: Create Loki Config Directory
      file:
        path: /etc/loki
        state: directory
        mode: "0755"

    - name: Ensure Loki owns its data and config
      file:
        path: "{{ item }}"
        state: directory
        owner: loki
        group: loki
        mode: '0755'
        recurse: yes
      loop:
        - /etc/loki
        - /tmp/loki
        - /var/lib/lib

    - name: Download default Loki config (Shell version)
      shell: |
        curl -L "https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml" -o /etc/loki/loki-config.yaml
      args:
        creates: /etc/loki/loki-config.yaml

    - name: Unzip Loki binary
      unarchive:
        src: /tmp/loki.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'

    - name: Create Loki systemd service file
      copy:
        dest: /etc/systemd/system/loki.service
        content: |
          [Unit]
          Description=Loki log aggregation system
          After=network.target

          [Service]
          Type=simple
          User=loki
          Group=loki
          ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki/loki-config.yaml
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and Enable Loki
      systemd:
        name: loki
        state: started
        enabled: true
        daemon_reload: yes

   handlers:
    - name: Restart grafana
      systemd:
        name: grafana-server
        state: restarted
