[blue1_server]
10.100.2.7

[blue2_server]
10.100.3.7

[blue1_agents]
10.100.2.4
10.100.2.5
10.100.2.6

[blue2_agents]
10.100.3.4
10.100.3.5
10.100.3.6

[server:children]
blue1_server
blue2_server

[agents:children]
blue1_agents
blue2_agents

[agents:vars]
ansible_user=greyteam
ansible_ssh_pass=Hockey123!
ansible_sudo=Hockey123!
