---
team_domain_controller_ip: "10.100.2.11"

blue_team_admin_users:
  - herb_brooks
  - craig_patrick
  - jimmy_carter
  - eruzione
  - jim_craig

blue_team_local_users:
  - rob_mclanahan
  - mark_johnson
  - ken_morrow
  - dave_silk
  - jack_oh_callahan
  - dave_christian
  - buzz_schneider
  - bob_suter
