# WinRM settings for Blue Team Windows hosts.
ansible_connection: winrm
# ansible_user: "{{ bootstrap_user.username }}"
ansible_user: "ansible"
# ansible_password: "{{ bootstrap_user.password }}"
ansible_password: "DeployWindows123!"
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
