---
- name: Configure rsyslog clients for grayteam
  hosts: syslog_clients_gray
  become: true

  tasks:
    - name: Install rsyslog
      package:
        name: rsyslog
        state: present

    - name: Enable rsyslog service
      service:
        name: rsyslog
        enabled: yes
        state: started

    - name: Configure log forwarding to central server 
      copy:
        dest: /etc/rsyslog.d/90-forward.conf
        mode: '0644'
        content: |
          if $programname == 'scorecheck' then {
            *.* @@{{ hostvars[groups['syslog_central_blue1'][0]].ansible_host | default(groups['syslog_central_blue1'][0]) }}:514
            *.* @@{{ hostvars[groups['syslog_central_blue2'][0]].ansible_host | default(groups['syslog_central_blue2'][0]) }}:514
            stop
          }
      notify: Restart rsyslog

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted