[syslog_central]
10.100.2.8 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.8 ansible_user=cyberrange ansible_password=Cyberrange123!

[syslog_clients_blue1]
10.100.2.3 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.4 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.5 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.6 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.7 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.9 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.10 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.2.11 ansible_user=cyberrange ansible_password=Cyberrange123!

[syslog_clients_blue2]
10.100.3.3 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.4 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.5 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.6 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.7 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.9 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.10 ansible_user=cyberrange ansible_password=Cyberrange123!
10.100.3.11 ansible_user=cyberrange ansible_password=Cyberrange123!

[syslog_clients_gray]
10.100.0.30 ansible_user=cyberrange ansible_password=Cyberrange123!

