---
# Author: Caroline Richards
# Email: cpr9499@rit.edu

# This playbook deploys a web stack on a Linux host with Nginx, MySQL, and PHP
- name: Install Nginx and PHP packages
  apt: 
    name: 
      - nginx
      - php-fpm
    state: present
    update_cache: yes

# PHP
- name: Start and enable PHP-FPM
  service:
    name: php7.4-fpm
    state: started
    enabled: yes

# Nginx Setup
- name: Start and enable Nginx
  service: 
    name: nginx
    state: started
    enabled: yes

- name: Ensure web root directory exists
  file:
      path: "{{ web_stack.web_root }}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'

- name: Copy website files
  copy: 
    src: "{{ item }}"
    dest: "{{ web_stack.web_root }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: '0644'
  loop:
    - index.php
    - style.css
    - score.php
    - door.php
  
- name: Deploy config.php
  template:
    src: config.php.j2
    dest: "{{ web_stack.web_root }}/config.php"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Copy Nginx configuration
  copy: 
    src: nginx.conf
    dest: /etc/nginx/sites-available/miracle_ice
    mode: '0644'

- name: Enable nginx site
  file: 
    src: /etc/nginx/sites-available/miracle_ice
    dest: /etc/nginx/sites-enabled/miracle_ice
    state: link

- name: Remove default nginx site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx 
  service: 
    name: nginx
    state: restarted