---
ansible_connection: ssh
ansible_user: greyteam
ansible_password: <LINUX_PASSWORD>
ansible_become: true
ansible_become_method: sudo

wazuh_repo_url: "https://packages.wazuh.com/4.x/apt/"
wazuh_repo_key_url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
wazuh_agent_config_path: "/var/ossec/etc/ossec.conf"
wazuh_agent_service_name: "wazuh-agent"