[blue1]
usa-box-01 ansible_host=10.100.2.3
usa-box-02 ansible_host=10.100.2.4
usa-box-03 ansible_host=10.100.2.5
usa-box-04 ansible_host=10.100.2.6
usa-box-05 ansible_host=10.100.2.7
usa-box-06 ansible_host=10.100.2.8

[blue2]
ussr-box-01 ansible_host=10.100.3.3
ussr-box-02 ansible_host=10.100.3.4
ussr-box-03 ansible_host=10.100.3.5
ussr-box-04 ansible_host=10.100.3.6
ussr-box-05 ansible_host=10.100.3.7
ussr-box-06 ansible_host=10.100.3.8

[linux:children]
blue1
blue2