[windows]
winhost ansible_host=192.168.1.100

[windows:vars]
ansible_user=greyteam
ansible_password=Hockey123!
ansible_connection=winrm
ansible_port=5985

ansible-galaxy collection install ansible.windows
ansible-galaxy collection install community.windows