[blue1_linux]
blue1-cross-check ansible_host=10.100.2.3
blue1-hat-trick ansible_host=10.100.2.4
blue1-triple-dere ansible_host=10.100.2.5
blue1-toe-drag ansible_host=10.100.2.6
blue1-clapper ansible_host=10.100.2.7
blue1-backcheck ansible_host=10.100.2.8

[blue1_windows]
blue1-dump-n-chase ansible_host=10.100.2.9
blue1-snapshot ansible_host=10.100.2.10
blue1-bardown ansible_host=10.100.2.11

[blue2_linux]
blue2-cross-check ansible_host=10.100.3.3
blue2-hat-trick ansible_host=10.100.3.4
blue2-triple-dere ansible_host=10.100.3.5
blue2-toe-drag ansible_host=10.100.3.6
blue2-clapper ansible_host=10.100.3.7
blue2-backcheck ansible_host=10.100.3.8

[blue2_windows]
blue2-dump-n-chase ansible_host=10.100.3.9
blue2-snapshot ansible_host=10.100.3.10
blue2-bardown ansible_host=10.100.3.11

[linux:children]
blue1_linux
blue2_linux

[windows:children]
blue1_windows
blue2_windows

[blue1:children]
blue1_linux
blue1_windows

[blue2:children]
blue2_linux
blue2_windows