---
- name: Install Tailscale on Linux hosts
  hosts: linux
  gather_facts: true
  vars_files:
    - secrets.yml
  roles:
    - tailscale_linux

- name: Install Tailscale on Windows hosts
  hosts: windows
  gather_facts: false
  vars_files:
    - secrets.yml
  roles:
    - tailscale_windows
