[linux]
linux-01 ansible_host=10.100.2.3
linux-02 ansible_host=10.100.2.4
linux-03 ansible_host=10.100.2.5
linux-04 ansible_host=10.100.2.6
linux-05 ansible_host=10.100.2.7
linux-06 ansible_host=10.100.2.8

linux-07 ansible_host=10.100.3.3
linux-08 ansible_host=10.100.3.4
linux-09 ansible_host=10.100.3.5
linux-10 ansible_host=10.100.3.6
linux-11 ansible_host=10.100.3.7
linux-12 ansible_host=10.100.3.8

[windows]
windows-01 ansible_host=10.100.2.9
windows-02 ansible_host=10.100.2.10
windows-03 ansible_host=10.100.2.11

windows-04 ansible_host=10.100.3.9
windows-05 ansible_host=10.100.3.10
windows-06 ansible_host=10.100.3.11

[linux_subnet_routers]
subnet-router-01 ansible_host=10.100.2.172 tailscale_advertise_routes=10.100.2.0/24
subnet-router-02 ansible_host=10.100.3.103 tailscale_advertise_routes=10.100.3.0/24

[all:children]
linux
windows